#!/bin/bash

# NOTE: Run script with source (ie. source ~/Dependencies/pythonParaview

# Check to see if compiled VTK paths are set to PYTHONPATH variable

if [[ " :$PYTHONPATH:" == *"/opt/vtk/lib:/opt/vtk/lib/python2.7/site-packages"* ]]
then
 echo "Removing compiled VTK paths from PYTHONPATH..."
 PYTHONPATH=$(echo $PYTHONPATH | sed -e 's;:\?/opt/vtk/lib;;' -e 's;:\?/opt/vtk/lib/python2.7/site-packages;;')

else
 echo "Adding compiled VTK paths to PYTHONPATH..."
 PYTHONPATH=$PYTHONPATH:/opt/vtk/lib:/opt/vtk/lib/python2.7/site-packages

fi 

# done 
